# Generated by Django 4.1.3 on 2022-12-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMateo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
